name: Build
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/build.yml'
      - '**.swift'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - '**.swift'
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: swift test -v
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |-
          set -o pipefail && NSUnbufferedIO=YES xcodebuild test \
            -scheme ColorToolbox \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            -sdk iphonesimulator \
            | xcpretty
